---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/budgets":
    get:
      summary: list budgets
      tags:
      - Budgets
      responses:
        '200':
          description: successful
    post:
      summary: create budget
      tags:
      - Budgets
      responses:
        '200':
          description: successful
  "/api/budgets/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show budget
      tags:
      - Budgets
      responses:
        '200':
          description: successful
    patch:
      summary: update budget
      tags:
      - Budgets
      responses:
        '200':
          description: successful
    put:
      summary: update budget
      tags:
      - Budgets
      responses:
        '200':
          description: successful
    delete:
      summary: delete budget
      tags:
      - Budgets
      responses:
        '200':
          description: successful
  "/api/categories":
    get:
      summary: list categories
      tags:
      - Categories
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
      - Categories
      responses:
        '200':
          description: successful
  "/api/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Categories
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      tags:
      - Categories
      responses:
        '200':
          description: successful
    put:
      summary: update category
      tags:
      - Categories
      responses:
        '200':
          description: successful
    delete:
      summary: delete category
      tags:
      - Categories
      responses:
        '200':
          description: successful
  "/api/expenses":
    get:
      summary: list expenses
      tags:
      - Expenses
      responses:
        '200':
          description: successful
    post:
      summary: create expense
      tags:
      - Expenses
      responses:
        '200':
          description: successful
  "/api/expenses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show expense
      tags:
      - Expenses
      responses:
        '200':
          description: successful
    patch:
      summary: update expense
      tags:
      - Expenses
      responses:
        '200':
          description: successful
    put:
      summary: update expense
      tags:
      - Expenses
      responses:
        '200':
          description: successful
    delete:
      summary: delete expense
      tags:
      - Expenses
      responses:
        '200':
          description: successful
  "/api/incomes":
    get:
      summary: list incomes
      tags:
      - Incomes
      responses:
        '200':
          description: successful
    post:
      summary: create income
      tags:
      - Incomes
      responses:
        '200':
          description: successful
  "/api/incomes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show income
      tags:
      - Incomes
      responses:
        '200':
          description: successful
    patch:
      summary: update income
      tags:
      - Incomes
      responses:
        '200':
          description: successful
    put:
      summary: update income
      tags:
      - Incomes
      responses:
        '200':
          description: successful
    delete:
      summary: delete income
      tags:
      - Incomes
      responses:
        '200':
          description: successful
  "/users/cancel":
    get:
      summary: cancel registration
      tags:
      - Registrations
      responses:
        '200':
          description: successful
  "/users/sign_up":
    get:
      summary: new registration
      tags:
      - Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/users/edit":
    get:
      summary: edit registration
      tags:
      - Registrations
      responses:
        '200':
          description: successful
  "/users":
    patch:
      summary: update registration
      tags:
      - Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                current_password:
                  type: string
              required:
              - email
              - password
              - password_confirmation
              - current_password
    put:
      summary: update registration
      tags:
      - Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                current_password:
                  type: string
              required:
              - email
              - password
              - password_confirmation
              - current_password
    delete:
      summary: delete registration
      tags:
      - Registrations
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      tags:
      - Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/registrations":
    post:
      summary: create registration
      tags:
      - Registrations
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/users/sign_in":
    get:
      summary: new session
      tags:
      - Sessions
      responses:
        '200':
          description: successful
    post:
      summary: create session
      tags:
      - Sessions
      responses:
        '200':
          description: successful
  "/users/sign_out":
    delete:
      summary: delete session
      tags:
      - Sessions
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
